"""Report exports — turn agent markdown into downloadable PDF / DOCX files.

The PDF writer is dependency-free (hand-assembled PDF 1.4: Helvetica +
Courier, word-wrapped paragraphs, headings, bullets, page footers) so
exports work on every deployment, including the free tier. DOCX rendering
uses python-docx, which is already part of the document-parsing stack.
"""
import io
import re
from datetime import datetime, timezone

# ── markdown → simple block model ────────────────────────────────────────
# kinds: h1 | h2 | h3 | bullet | code | text | space
_BOLD = re.compile(r"\*\*(.+?)\*\*")
_INLINE_CODE = re.compile(r"`([^`]+)`")


def _clean(text: str) -> str:
    text = _BOLD.sub(r"\1", text)
    text = _INLINE_CODE.sub(r"\1", text)
    return text.strip()


def md_to_blocks(md: str) -> list[tuple[str, str]]:
    blocks: list[tuple[str, str]] = []
    in_code = False
    for raw in (md or "").splitlines():
        line = raw.rstrip()
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            blocks.append(("code", raw))
            continue
        if not line.strip():
            if blocks and blocks[-1][0] != "space":
                blocks.append(("space", ""))
            continue
        if line.startswith("### "):
            blocks.append(("h3", _clean(line[4:])))
        elif line.startswith("## "):
            blocks.append(("h2", _clean(line[3:])))
        elif line.startswith("# "):
            blocks.append(("h1", _clean(line[2:])))
        elif re.match(r"^\s*[-*•]\s+", line):
            blocks.append(("bullet", _clean(re.sub(r"^\s*[-*•]\s+", "", line))))
        elif re.match(r"^\s*\d+[.)]\s+", line):
            blocks.append(("bullet", _clean(line.strip())))
        else:
            blocks.append(("text", _clean(line)))
    return blocks


# ── dependency-free PDF ──────────────────────────────────────────────────
_PAGE_W, _PAGE_H = 595, 842  # A4 portrait, points
_MARGIN = 56
_FOOTER_Y = 34


def _esc(s: str) -> str:
    s = s.encode("latin-1", "replace").decode("latin-1")
    return s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def _wrap(text: str, size: float, width: float, mono: bool = False) -> list[str]:
    per_char = size * (0.60 if mono else 0.50)  # Helvetica/Courier average advance
    max_chars = max(12, int(width / per_char))
    words, lines, cur = text.split(" "), [], ""
    for w in words:
        candidate = f"{cur} {w}".strip()
        if len(candidate) <= max_chars:
            cur = candidate
        else:
            if cur:
                lines.append(cur)
            while len(w) > max_chars:  # unbreakable token
                lines.append(w[:max_chars])
                w = w[max_chars:]
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def build_pdf(title: str, md: str) -> bytes:
    usable = _PAGE_W - 2 * _MARGIN
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # layout pass → per-page list of (font, size, x, y, text)
    pages: list[list[tuple[str, float, float, float, str]]] = [[]]
    y = _PAGE_H - _MARGIN

    def newline(h: float) -> None:
        nonlocal y
        y -= h
        if y < _MARGIN + 20:
            pages.append([])
            y = _PAGE_H - _MARGIN

    def emit(font: str, size: float, text: str, x: float = _MARGIN, lead: float | None = None) -> None:
        newline(lead if lead is not None else size * 1.45)
        pages[-1].append((font, size, x, y, text))

    emit("F2", 19, title or "EAIOS Report", lead=19)
    emit("F1", 9.5, f"Generated by EAIOS · {stamp}", lead=16)
    newline(6)

    for kind, text in md_to_blocks(md):
        if kind == "space":
            newline(7)
        elif kind == "h1":
            newline(8)
            for seg in _wrap(text, 15.5, usable):
                emit("F2", 15.5, seg)
        elif kind == "h2":
            newline(6)
            for seg in _wrap(text, 13, usable):
                emit("F2", 13, seg)
        elif kind == "h3":
            newline(4)
            for seg in _wrap(text, 11.5, usable):
                emit("F2", 11.5, seg)
        elif kind == "bullet":
            segs = _wrap(text, 10.5, usable - 14)
            emit("F1", 10.5, "• " + segs[0], x=_MARGIN + 4)
            for seg in segs[1:]:
                emit("F1", 10.5, seg, x=_MARGIN + 14)
        elif kind == "code":
            for seg in _wrap(text or " ", 9, usable - 8, mono=True):
                emit("F3", 9, seg, x=_MARGIN + 4, lead=12)
        else:
            for seg in _wrap(text, 10.5, usable):
                emit("F1", 10.5, seg)

    # assemble PDF objects
    n_pages = len(pages)
    objects: list[bytes] = []

    def add(obj: bytes) -> int:
        objects.append(obj)
        return len(objects)  # 1-based object number

    font_base = 3 + 2 * n_pages  # catalog, pages, then (page,content)×n
    kids = " ".join(f"{3 + 2 * i} 0 R" for i in range(n_pages))
    add(b"<< /Type /Catalog /Pages 2 0 R >>")                                   # 1
    add(f"<< /Type /Pages /Kids [{kids}] /Count {n_pages} >>".encode())         # 2

    for i, items in enumerate(pages):
        page_no, content_no = 3 + 2 * i, 4 + 2 * i
        add((f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {_PAGE_W} {_PAGE_H}] "
             f"/Resources << /Font << /F1 {font_base} 0 R /F2 {font_base + 1} 0 R /F3 {font_base + 2} 0 R >> >> "
             f"/Contents {content_no} 0 R >>").encode())
        assert page_no == len(objects), "page numbering drifted"
        parts = ["BT"]
        for font, size, x, yy, text in items:
            parts.append(f"/{font} {size:.1f} Tf 1 0 0 1 {x:.1f} {yy:.1f} Tm ({_esc(text)}) Tj")
        parts.append(f"/F1 8.5 Tf 1 0 0 1 {_MARGIN:.1f} {_FOOTER_Y} Tm "
                     f"(EAIOS · page {i + 1} of {n_pages}) Tj".encode("latin-1", "replace").decode("latin-1"))
        parts.append("ET")
        stream = "\n".join(parts).encode("latin-1", "replace")
        add(b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream")

    add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")
    add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>")

    out = io.BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(out.tell())
        out.write(f"{i} 0 obj\n".encode())
        out.write(obj)
        out.write(b"\nendobj\n")
    xref_at = out.tell()
    out.write(f"xref\n0 {len(objects) + 1}\n".encode())
    out.write(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.write(f"{off:010d} 00000 n \n".encode())
    out.write(f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF".encode())
    return out.getvalue()


# ── DOCX (python-docx — already a core dependency) ───────────────────────
def build_docx(title: str, md: str) -> bytes:
    import docx
    from docx.shared import Pt

    doc = docx.Document()
    doc.add_heading(title or "EAIOS Report", level=0)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    meta = doc.add_paragraph(f"Generated by EAIOS · {stamp}")
    meta.runs[0].font.size = Pt(8.5)

    for kind, text in md_to_blocks(md):
        if kind == "space":
            continue
        if kind == "h1":
            doc.add_heading(text, level=1)
        elif kind == "h2":
            doc.add_heading(text, level=2)
        elif kind == "h3":
            doc.add_heading(text, level=3)
        elif kind == "bullet":
            doc.add_paragraph(text, style="List Bullet")
        elif kind == "code":
            p = doc.add_paragraph(text or " ")
            for run in p.runs:
                run.font.name = "Courier New"
                run.font.size = Pt(9)
        else:
            doc.add_paragraph(text)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def safe_filename(title: str, ext: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", (title or "eaios-report")).strip("-").lower()[:60] or "eaios-report"
    return f"{slug}.{ext}"
